/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.um.qa.oshs.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the customer service. Represents a row in the &quot;oshs_customer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.um.qa.oshs.sb.model.impl.customerModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.um.qa.oshs.sb.model.impl.customerImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see customer
 * @generated
 */
@ProviderType
public interface customerModel
	extends BaseModel<customer>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a customer model instance should use the {@link customer} interface instead.
	 */

	/**
	 * Returns the primary key of this customer.
	 *
	 * @return the primary key of this customer
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this customer.
	 *
	 * @param primaryKey the primary key of this customer
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this customer.
	 *
	 * @return the uuid of this customer
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this customer.
	 *
	 * @param uuid the uuid of this customer
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the customer ID of this customer.
	 *
	 * @return the customer ID of this customer
	 */
	public long getCustomerID();

	/**
	 * Sets the customer ID of this customer.
	 *
	 * @param customerID the customer ID of this customer
	 */
	public void setCustomerID(long customerID);

	/**
	 * Returns the group ID of this customer.
	 *
	 * @return the group ID of this customer
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this customer.
	 *
	 * @param groupId the group ID of this customer
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this customer.
	 *
	 * @return the company ID of this customer
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this customer.
	 *
	 * @param companyId the company ID of this customer
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this customer.
	 *
	 * @return the user ID of this customer
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this customer.
	 *
	 * @param userId the user ID of this customer
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this customer.
	 *
	 * @return the user uuid of this customer
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this customer.
	 *
	 * @param userUuid the user uuid of this customer
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this customer.
	 *
	 * @return the user name of this customer
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this customer.
	 *
	 * @param userName the user name of this customer
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this customer.
	 *
	 * @return the create date of this customer
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this customer.
	 *
	 * @param createDate the create date of this customer
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this customer.
	 *
	 * @return the modified date of this customer
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this customer.
	 *
	 * @param modifiedDate the modified date of this customer
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the first name of this customer.
	 *
	 * @return the first name of this customer
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this customer.
	 *
	 * @param firstName the first name of this customer
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the middle name of this customer.
	 *
	 * @return the middle name of this customer
	 */
	@AutoEscape
	public String getMiddleName();

	/**
	 * Sets the middle name of this customer.
	 *
	 * @param middleName the middle name of this customer
	 */
	public void setMiddleName(String middleName);

	/**
	 * Returns the last name of this customer.
	 *
	 * @return the last name of this customer
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this customer.
	 *
	 * @param lastName the last name of this customer
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the display name of this customer.
	 *
	 * @return the display name of this customer
	 */
	@AutoEscape
	public String getDisplayName();

	/**
	 * Sets the display name of this customer.
	 *
	 * @param displayName the display name of this customer
	 */
	public void setDisplayName(String displayName);

	/**
	 * Returns the salutation of this customer.
	 *
	 * @return the salutation of this customer
	 */
	@AutoEscape
	public String getSalutation();

	/**
	 * Sets the salutation of this customer.
	 *
	 * @param salutation the salutation of this customer
	 */
	public void setSalutation(String salutation);

	/**
	 * Returns the address1 of this customer.
	 *
	 * @return the address1 of this customer
	 */
	@AutoEscape
	public String getAddress1();

	/**
	 * Sets the address1 of this customer.
	 *
	 * @param address1 the address1 of this customer
	 */
	public void setAddress1(String address1);

	/**
	 * Returns the address2 of this customer.
	 *
	 * @return the address2 of this customer
	 */
	@AutoEscape
	public String getAddress2();

	/**
	 * Sets the address2 of this customer.
	 *
	 * @param address2 the address2 of this customer
	 */
	public void setAddress2(String address2);

	/**
	 * Returns the address3 of this customer.
	 *
	 * @return the address3 of this customer
	 */
	public long getAddress3();

	/**
	 * Sets the address3 of this customer.
	 *
	 * @param address3 the address3 of this customer
	 */
	public void setAddress3(long address3);

	/**
	 * Returns the city of this customer.
	 *
	 * @return the city of this customer
	 */
	public long getCity();

	/**
	 * Sets the city of this customer.
	 *
	 * @param city the city of this customer
	 */
	public void setCity(long city);

	/**
	 * Returns the country of this customer.
	 *
	 * @return the country of this customer
	 */
	public long getCountry();

	/**
	 * Sets the country of this customer.
	 *
	 * @param country the country of this customer
	 */
	public void setCountry(long country);

	/**
	 * Returns the state of this customer.
	 *
	 * @return the state of this customer
	 */
	public long getState();

	/**
	 * Sets the state of this customer.
	 *
	 * @param state the state of this customer
	 */
	public void setState(long state);

	/**
	 * Returns the zip of this customer.
	 *
	 * @return the zip of this customer
	 */
	public long getZip();

	/**
	 * Sets the zip of this customer.
	 *
	 * @param zip the zip of this customer
	 */
	public void setZip(long zip);

	/**
	 * Returns the phone of this customer.
	 *
	 * @return the phone of this customer
	 */
	public long getPhone();

	/**
	 * Sets the phone of this customer.
	 *
	 * @param phone the phone of this customer
	 */
	public void setPhone(long phone);

}