/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.um.qa.oshs.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the order service. Represents a row in the &quot;oshs_order&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.um.qa.oshs.sb.model.impl.orderModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.um.qa.oshs.sb.model.impl.orderImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see order
 * @generated
 */
@ProviderType
public interface orderModel
	extends BaseModel<order>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a order model instance should use the {@link order} interface instead.
	 */

	/**
	 * Returns the primary key of this order.
	 *
	 * @return the primary key of this order
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this order.
	 *
	 * @param primaryKey the primary key of this order
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this order.
	 *
	 * @return the uuid of this order
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this order.
	 *
	 * @param uuid the uuid of this order
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the order ID of this order.
	 *
	 * @return the order ID of this order
	 */
	public long getOrderID();

	/**
	 * Sets the order ID of this order.
	 *
	 * @param orderID the order ID of this order
	 */
	public void setOrderID(long orderID);

	/**
	 * Returns the group ID of this order.
	 *
	 * @return the group ID of this order
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this order.
	 *
	 * @param groupId the group ID of this order
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this order.
	 *
	 * @return the company ID of this order
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this order.
	 *
	 * @param companyId the company ID of this order
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this order.
	 *
	 * @return the user ID of this order
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this order.
	 *
	 * @param userId the user ID of this order
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this order.
	 *
	 * @return the user uuid of this order
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this order.
	 *
	 * @param userUuid the user uuid of this order
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this order.
	 *
	 * @return the user name of this order
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this order.
	 *
	 * @param userName the user name of this order
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this order.
	 *
	 * @return the create date of this order
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this order.
	 *
	 * @param createDate the create date of this order
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this order.
	 *
	 * @return the modified date of this order
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this order.
	 *
	 * @param modifiedDate the modified date of this order
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this order.
	 *
	 * @return the status of this order
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this order.
	 *
	 * @param status the status of this order
	 */
	public void setStatus(String status);

	/**
	 * Returns the product ID of this order.
	 *
	 * @return the product ID of this order
	 */
	public long getProductID();

	/**
	 * Sets the product ID of this order.
	 *
	 * @param productID the product ID of this order
	 */
	public void setProductID(long productID);

	/**
	 * Returns the quantity of this order.
	 *
	 * @return the quantity of this order
	 */
	public long getQuantity();

	/**
	 * Sets the quantity of this order.
	 *
	 * @param quantity the quantity of this order
	 */
	public void setQuantity(long quantity);

	/**
	 * Returns the total of this order.
	 *
	 * @return the total of this order
	 */
	public float getTotal();

	/**
	 * Sets the total of this order.
	 *
	 * @param total the total of this order
	 */
	public void setTotal(float total);

	/**
	 * Returns the customer ID of this order.
	 *
	 * @return the customer ID of this order
	 */
	public long getCustomerID();

	/**
	 * Sets the customer ID of this order.
	 *
	 * @param customerID the customer ID of this order
	 */
	public void setCustomerID(long customerID);

}