/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.um.qa.oshs.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the staff service. Represents a row in the &quot;oshs_staff&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.um.qa.oshs.sb.model.impl.staffModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.um.qa.oshs.sb.model.impl.staffImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see staff
 * @generated
 */
@ProviderType
public interface staffModel
	extends BaseModel<staff>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a staff model instance should use the {@link staff} interface instead.
	 */

	/**
	 * Returns the primary key of this staff.
	 *
	 * @return the primary key of this staff
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this staff.
	 *
	 * @param primaryKey the primary key of this staff
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this staff.
	 *
	 * @return the uuid of this staff
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this staff.
	 *
	 * @param uuid the uuid of this staff
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the staff ID of this staff.
	 *
	 * @return the staff ID of this staff
	 */
	public long getStaffID();

	/**
	 * Sets the staff ID of this staff.
	 *
	 * @param staffID the staff ID of this staff
	 */
	public void setStaffID(long staffID);

	/**
	 * Returns the group ID of this staff.
	 *
	 * @return the group ID of this staff
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this staff.
	 *
	 * @param groupId the group ID of this staff
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this staff.
	 *
	 * @return the company ID of this staff
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this staff.
	 *
	 * @param companyId the company ID of this staff
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this staff.
	 *
	 * @return the user ID of this staff
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this staff.
	 *
	 * @param userId the user ID of this staff
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this staff.
	 *
	 * @return the user uuid of this staff
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this staff.
	 *
	 * @param userUuid the user uuid of this staff
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this staff.
	 *
	 * @return the user name of this staff
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this staff.
	 *
	 * @param userName the user name of this staff
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this staff.
	 *
	 * @return the create date of this staff
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this staff.
	 *
	 * @param createDate the create date of this staff
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this staff.
	 *
	 * @return the modified date of this staff
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this staff.
	 *
	 * @param modifiedDate the modified date of this staff
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the first name of this staff.
	 *
	 * @return the first name of this staff
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this staff.
	 *
	 * @param firstName the first name of this staff
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the middle name of this staff.
	 *
	 * @return the middle name of this staff
	 */
	@AutoEscape
	public String getMiddleName();

	/**
	 * Sets the middle name of this staff.
	 *
	 * @param middleName the middle name of this staff
	 */
	public void setMiddleName(String middleName);

	/**
	 * Returns the last name of this staff.
	 *
	 * @return the last name of this staff
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this staff.
	 *
	 * @param lastName the last name of this staff
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the display name of this staff.
	 *
	 * @return the display name of this staff
	 */
	@AutoEscape
	public String getDisplayName();

	/**
	 * Sets the display name of this staff.
	 *
	 * @param displayName the display name of this staff
	 */
	public void setDisplayName(String displayName);

	/**
	 * Returns the salutation of this staff.
	 *
	 * @return the salutation of this staff
	 */
	@AutoEscape
	public String getSalutation();

	/**
	 * Sets the salutation of this staff.
	 *
	 * @param salutation the salutation of this staff
	 */
	public void setSalutation(String salutation);

	/**
	 * Returns the staff type of this staff.
	 *
	 * @return the staff type of this staff
	 */
	@AutoEscape
	public String getStaffType();

	/**
	 * Sets the staff type of this staff.
	 *
	 * @param staffType the staff type of this staff
	 */
	public void setStaffType(String staffType);

	/**
	 * Returns the designation of this staff.
	 *
	 * @return the designation of this staff
	 */
	@AutoEscape
	public String getDesignation();

	/**
	 * Sets the designation of this staff.
	 *
	 * @param designation the designation of this staff
	 */
	public void setDesignation(String designation);

	/**
	 * Returns the qualifcation of this staff.
	 *
	 * @return the qualifcation of this staff
	 */
	@AutoEscape
	public String getQualifcation();

	/**
	 * Sets the qualifcation of this staff.
	 *
	 * @param qualifcation the qualifcation of this staff
	 */
	public void setQualifcation(String qualifcation);

	/**
	 * Returns the experience of this staff.
	 *
	 * @return the experience of this staff
	 */
	public long getExperience();

	/**
	 * Sets the experience of this staff.
	 *
	 * @param experience the experience of this staff
	 */
	public void setExperience(long experience);

}