/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.um.qa.oshs.sb.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.um.qa.oshs.sb.model.order;
import com.um.qa.oshs.sb.model.orderModel;
import com.um.qa.oshs.sb.model.orderSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the order service. Represents a row in the &quot;oshs_order&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>orderModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link orderImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see orderImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class orderModelImpl extends BaseModelImpl<order> implements orderModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a order model instance should use the <code>order</code> interface instead.
	 */
	public static final String TABLE_NAME = "oshs_order";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"orderID", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.VARCHAR}, {"productID", Types.BIGINT},
		{"quantity", Types.BIGINT}, {"total", Types.FLOAT},
		{"customerID", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("orderID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("productID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("quantity", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("total", Types.FLOAT);
		TABLE_COLUMNS_MAP.put("customerID", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table oshs_order (uuid_ VARCHAR(75) null,orderID LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status VARCHAR(75) null,productID LONG,quantity LONG,total DOUBLE,customerID LONG)";

	public static final String TABLE_SQL_DROP = "drop table oshs_order";

	public static final String ORDER_BY_JPQL =
		" ORDER BY order_.createDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY oshs_order.createDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long CREATEDATE_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static order toModel(orderSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		order model = new orderImpl();

		model.setUuid(soapModel.getUuid());
		model.setOrderID(soapModel.getOrderID());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setProductID(soapModel.getProductID());
		model.setQuantity(soapModel.getQuantity());
		model.setTotal(soapModel.getTotal());
		model.setCustomerID(soapModel.getCustomerID());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<order> toModels(orderSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<order> models = new ArrayList<order>(soapModels.length);

		for (orderSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public orderModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _orderID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setOrderID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _orderID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return order.class;
	}

	@Override
	public String getModelClassName() {
		return order.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<order, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<order, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<order, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((order)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<order, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<order, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((order)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<order, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<order, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<order, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<order, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<order, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<order, Object>>();
		Map<String, BiConsumer<order, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<order, ?>>();

		attributeGetterFunctions.put("uuid", order::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<order, String>)order::setUuid);
		attributeGetterFunctions.put("orderID", order::getOrderID);
		attributeSetterBiConsumers.put(
			"orderID", (BiConsumer<order, Long>)order::setOrderID);
		attributeGetterFunctions.put("groupId", order::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<order, Long>)order::setGroupId);
		attributeGetterFunctions.put("companyId", order::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<order, Long>)order::setCompanyId);
		attributeGetterFunctions.put("userId", order::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<order, Long>)order::setUserId);
		attributeGetterFunctions.put("userName", order::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<order, String>)order::setUserName);
		attributeGetterFunctions.put("createDate", order::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<order, Date>)order::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", order::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<order, Date>)order::setModifiedDate);
		attributeGetterFunctions.put("status", order::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<order, String>)order::setStatus);
		attributeGetterFunctions.put("productID", order::getProductID);
		attributeSetterBiConsumers.put(
			"productID", (BiConsumer<order, Long>)order::setProductID);
		attributeGetterFunctions.put("quantity", order::getQuantity);
		attributeSetterBiConsumers.put(
			"quantity", (BiConsumer<order, Long>)order::setQuantity);
		attributeGetterFunctions.put("total", order::getTotal);
		attributeSetterBiConsumers.put(
			"total", (BiConsumer<order, Float>)order::setTotal);
		attributeGetterFunctions.put("customerID", order::getCustomerID);
		attributeSetterBiConsumers.put(
			"customerID", (BiConsumer<order, Long>)order::setCustomerID);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getOrderID() {
		return _orderID;
	}

	@Override
	public void setOrderID(long orderID) {
		_orderID = orderID;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		_status = status;
	}

	@JSON
	@Override
	public long getProductID() {
		return _productID;
	}

	@Override
	public void setProductID(long productID) {
		_productID = productID;
	}

	@JSON
	@Override
	public long getQuantity() {
		return _quantity;
	}

	@Override
	public void setQuantity(long quantity) {
		_quantity = quantity;
	}

	@JSON
	@Override
	public float getTotal() {
		return _total;
	}

	@Override
	public void setTotal(float total) {
		_total = total;
	}

	@JSON
	@Override
	public long getCustomerID() {
		return _customerID;
	}

	@Override
	public void setCustomerID(long customerID) {
		_customerID = customerID;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(order.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), order.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public order toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (order)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		orderImpl orderImpl = new orderImpl();

		orderImpl.setUuid(getUuid());
		orderImpl.setOrderID(getOrderID());
		orderImpl.setGroupId(getGroupId());
		orderImpl.setCompanyId(getCompanyId());
		orderImpl.setUserId(getUserId());
		orderImpl.setUserName(getUserName());
		orderImpl.setCreateDate(getCreateDate());
		orderImpl.setModifiedDate(getModifiedDate());
		orderImpl.setStatus(getStatus());
		orderImpl.setProductID(getProductID());
		orderImpl.setQuantity(getQuantity());
		orderImpl.setTotal(getTotal());
		orderImpl.setCustomerID(getCustomerID());

		orderImpl.resetOriginalValues();

		return orderImpl;
	}

	@Override
	public int compareTo(order order) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), order.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof order)) {
			return false;
		}

		order order = (order)obj;

		long primaryKey = order.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		orderModelImpl orderModelImpl = this;

		orderModelImpl._originalUuid = orderModelImpl._uuid;

		orderModelImpl._originalGroupId = orderModelImpl._groupId;

		orderModelImpl._setOriginalGroupId = false;

		orderModelImpl._originalCompanyId = orderModelImpl._companyId;

		orderModelImpl._setOriginalCompanyId = false;

		orderModelImpl._setModifiedDate = false;

		orderModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<order> toCacheModel() {
		orderCacheModel orderCacheModel = new orderCacheModel();

		orderCacheModel.uuid = getUuid();

		String uuid = orderCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			orderCacheModel.uuid = null;
		}

		orderCacheModel.orderID = getOrderID();

		orderCacheModel.groupId = getGroupId();

		orderCacheModel.companyId = getCompanyId();

		orderCacheModel.userId = getUserId();

		orderCacheModel.userName = getUserName();

		String userName = orderCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			orderCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			orderCacheModel.createDate = createDate.getTime();
		}
		else {
			orderCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			orderCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			orderCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		orderCacheModel.status = getStatus();

		String status = orderCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			orderCacheModel.status = null;
		}

		orderCacheModel.productID = getProductID();

		orderCacheModel.quantity = getQuantity();

		orderCacheModel.total = getTotal();

		orderCacheModel.customerID = getCustomerID();

		return orderCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<order, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<order, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<order, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((order)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<order, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<order, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<order, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((order)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		order.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		order.class, ModelWrapper.class
	};
	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _orderID;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _status;
	private long _productID;
	private long _quantity;
	private float _total;
	private long _customerID;
	private long _columnBitmask;
	private order _escapedModel;

}