/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.um.qa.oshs.sb.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.um.qa.oshs.sb.model.product;
import com.um.qa.oshs.sb.model.productModel;
import com.um.qa.oshs.sb.model.productSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the product service. Represents a row in the &quot;oshs_product&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>productModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link productImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see productImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class productModelImpl
	extends BaseModelImpl<product> implements productModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a product model instance should use the <code>product</code> interface instead.
	 */
	public static final String TABLE_NAME = "oshs_product";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"productID", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"productName", Types.BIGINT}, {"images", Types.VARCHAR},
		{"description", Types.BIGINT}, {"quantity", Types.FLOAT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("productID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("productName", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("images", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("quantity", Types.FLOAT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table oshs_product (uuid_ VARCHAR(75) null,productID LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,productName LONG,images VARCHAR(75) null,description LONG,quantity DOUBLE)";

	public static final String TABLE_SQL_DROP = "drop table oshs_product";

	public static final String ORDER_BY_JPQL =
		" ORDER BY product.productName ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY oshs_product.productName ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long PRODUCTNAME_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static product toModel(productSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		product model = new productImpl();

		model.setUuid(soapModel.getUuid());
		model.setProductID(soapModel.getProductID());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setProductName(soapModel.getProductName());
		model.setImages(soapModel.getImages());
		model.setDescription(soapModel.getDescription());
		model.setQuantity(soapModel.getQuantity());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<product> toModels(productSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<product> models = new ArrayList<product>(soapModels.length);

		for (productSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public productModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _productID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProductID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _productID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return product.class;
	}

	@Override
	public String getModelClassName() {
		return product.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<product, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<product, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<product, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((product)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<product, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<product, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(product)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<product, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<product, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<product, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<product, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<product, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<product, Object>>();
		Map<String, BiConsumer<product, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<product, ?>>();

		attributeGetterFunctions.put("uuid", product::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<product, String>)product::setUuid);
		attributeGetterFunctions.put("productID", product::getProductID);
		attributeSetterBiConsumers.put(
			"productID", (BiConsumer<product, Long>)product::setProductID);
		attributeGetterFunctions.put("groupId", product::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<product, Long>)product::setGroupId);
		attributeGetterFunctions.put("companyId", product::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<product, Long>)product::setCompanyId);
		attributeGetterFunctions.put("userId", product::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<product, Long>)product::setUserId);
		attributeGetterFunctions.put("userName", product::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<product, String>)product::setUserName);
		attributeGetterFunctions.put("createDate", product::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<product, Date>)product::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", product::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<product, Date>)product::setModifiedDate);
		attributeGetterFunctions.put("productName", product::getProductName);
		attributeSetterBiConsumers.put(
			"productName", (BiConsumer<product, Long>)product::setProductName);
		attributeGetterFunctions.put("images", product::getImages);
		attributeSetterBiConsumers.put(
			"images", (BiConsumer<product, String>)product::setImages);
		attributeGetterFunctions.put("description", product::getDescription);
		attributeSetterBiConsumers.put(
			"description", (BiConsumer<product, Long>)product::setDescription);
		attributeGetterFunctions.put("quantity", product::getQuantity);
		attributeSetterBiConsumers.put(
			"quantity", (BiConsumer<product, Float>)product::setQuantity);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getProductID() {
		return _productID;
	}

	@Override
	public void setProductID(long productID) {
		_productID = productID;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getProductName() {
		return _productName;
	}

	@Override
	public void setProductName(long productName) {
		_columnBitmask = -1L;

		_productName = productName;
	}

	@JSON
	@Override
	public String getImages() {
		if (_images == null) {
			return "";
		}
		else {
			return _images;
		}
	}

	@Override
	public void setImages(String images) {
		_images = images;
	}

	@JSON
	@Override
	public long getDescription() {
		return _description;
	}

	@Override
	public void setDescription(long description) {
		_description = description;
	}

	@JSON
	@Override
	public float getQuantity() {
		return _quantity;
	}

	@Override
	public void setQuantity(float quantity) {
		_quantity = quantity;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(product.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), product.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public product toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (product)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		productImpl productImpl = new productImpl();

		productImpl.setUuid(getUuid());
		productImpl.setProductID(getProductID());
		productImpl.setGroupId(getGroupId());
		productImpl.setCompanyId(getCompanyId());
		productImpl.setUserId(getUserId());
		productImpl.setUserName(getUserName());
		productImpl.setCreateDate(getCreateDate());
		productImpl.setModifiedDate(getModifiedDate());
		productImpl.setProductName(getProductName());
		productImpl.setImages(getImages());
		productImpl.setDescription(getDescription());
		productImpl.setQuantity(getQuantity());

		productImpl.resetOriginalValues();

		return productImpl;
	}

	@Override
	public int compareTo(product product) {
		int value = 0;

		if (getProductName() < product.getProductName()) {
			value = -1;
		}
		else if (getProductName() > product.getProductName()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof product)) {
			return false;
		}

		product product = (product)obj;

		long primaryKey = product.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		productModelImpl productModelImpl = this;

		productModelImpl._originalUuid = productModelImpl._uuid;

		productModelImpl._originalGroupId = productModelImpl._groupId;

		productModelImpl._setOriginalGroupId = false;

		productModelImpl._originalCompanyId = productModelImpl._companyId;

		productModelImpl._setOriginalCompanyId = false;

		productModelImpl._setModifiedDate = false;

		productModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<product> toCacheModel() {
		productCacheModel productCacheModel = new productCacheModel();

		productCacheModel.uuid = getUuid();

		String uuid = productCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			productCacheModel.uuid = null;
		}

		productCacheModel.productID = getProductID();

		productCacheModel.groupId = getGroupId();

		productCacheModel.companyId = getCompanyId();

		productCacheModel.userId = getUserId();

		productCacheModel.userName = getUserName();

		String userName = productCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			productCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			productCacheModel.createDate = createDate.getTime();
		}
		else {
			productCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			productCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			productCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		productCacheModel.productName = getProductName();

		productCacheModel.images = getImages();

		String images = productCacheModel.images;

		if ((images != null) && (images.length() == 0)) {
			productCacheModel.images = null;
		}

		productCacheModel.description = getDescription();

		productCacheModel.quantity = getQuantity();

		return productCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<product, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<product, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<product, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((product)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<product, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<product, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<product, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((product)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		product.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		product.class, ModelWrapper.class
	};
	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _productID;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _productName;
	private String _images;
	private long _description;
	private float _quantity;
	private long _columnBitmask;
	private product _escapedModel;

}